### ISSUE TITLE
Add Storage::startup()

### ISSUE THREAD

**Issue by v-dogg** [agavi/agavi#101]
Storage implementations need a uniform startup procedure. Currently [SessionStorage](http://github.com/agavi/agavi/wiki/SessionStorage) uses a special autoStart function and it's not a pretty hack at all.

to do:
- Storage::startup()
- rename [SessionStorage](http://github.com/agavi/agavi/wiki/SessionStorage)::autoStart to startup
- remove [SessionStorage](http://github.com/agavi/agavi/wiki/SessionStorage)::autoStart hack from Context::initialize and add startup handling

**Comment by linuxjackto1** [comment]
thanks www.movied.org
