### ISSUE TITLE
Add namespaces support to Request attributes

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#104]
This way, we can safely isolate attributes according to their origin and guarantee secure communication between components. Two examples:
- The [CachingExecutionFilter](http://github.com/agavi/agavi/wiki/CachingExecutionFilter) would set the caching status for each action executed in the `org/agavi/filter/CachingExecutionFilter`1. This info could be used later by a !AccessLogFilter or so to add the caching status of a request to the access logfile.
- The execution of the [FormPopulationFilter](http://github.com/agavi/agavi/wiki/FormPopulationFilter) could be prevented or explicitely forced by setting an attribute in the `org/agavi/filter/FormPopulationFilter` namespace.
  The default namespace will be `org/agavi/request/Request/attributes`

**Comment by linuxjackto1** [comment]
thanks www.movied.org
