### ISSUE TITLE
webapp/cache folder should use subdirs

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#106]
So... configs are stored in webapp/cache/config, caching execution filter stores the stuff in webapp/cache/content, smarty stores the compiled templates in webapp/cache/templates_smarty. agavi.php will be changed so it just clears the cache using some [RecursiveIteratorIterator](http://github.com/agavi/agavi/wiki/RecursiveIteratorIterator)/RecursiveDirectoryIterator magic (put that into util.php). subdir names are hardcoded in the classes (`AG_CACHE_DIR . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR . <filename>`)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
