### ISSUE TITLE
Consider moving attributes/namespaces functionality into a separate class

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#111]
class [AttributesHolder](http://github.com/agavi/agavi/wiki/AttributesHolder) extends [ParameterHolder](http://github.com/agavi/agavi/wiki/ParameterHolder) and
class [NamespacesAttributesHolder](http://github.com/agavi/agavi/wiki/NamespacesAttributesHolder) extends Parameterholder

this way, we don't have to maintain multiple code bases for that stuff. faster, too.

it would mean we have to change AG_USER_NAMESPACE and the new AG_REQUEST_NAMESPACE into one constant, AG_DEFAULT_NAMESPACE; but that's okay IMO.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
