### ISSUE TITLE
Switch arguments in genUrl()

### ISSUE THREAD

**Issue by shoan** [agavi/agavi#112]
http://trac.agavi.org/trac.cgi/browser/trunk/src/controller/WebController.class.php#L47

I think the arguments for 

```
public function genURL ($url = null, $parameters = array())
```

should be

```
public function genURL ( $parameters = array(), $url = null)
```

It is not necessary to pass $url each time. Moreover the function does have a fallback.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
