### ISSUE TITLE
Change bookstrapping method

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#122]
The current way where Agavi implicitely starts up when agavi.php (see #123) isn't the very best option. Since we'll introduce a registry, we'd have to split the current loading of Agavi into two parts, so we change this to (index.php):

```
  require('agavi/Agavi.php');
  require('../webapp/config.php');
  Agavi::bookstrap('environment');
  Context::getInstance('web')->getController()->dispatch();
```

yep, that also means a class "Agavi" which does the most basic stuff now.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
