### ISSUE TITLE
CompileConfigHandler is too greedy

### ISSUE THREAD

**Issue by bmatheny** [agavi/agavi#127]
The [CompileConfigHandler](http://github.com/agavi/agavi/wiki/CompileConfigHandler) in agavi 0.10 is too greedy on its regexes (lines 123-129). They also match urls (http://www.google.com gets matched as a comment) and xml (<?xml gets matched as a php start tag).

To replicate, create a file that includes a line like: $foo = "http://www.google.com"; and put it in the compile.ini then clear the cache dir. You will notice that that line now causes a fatal error since it is now just $foo = "http:

**Comment by linuxjackto1** [comment]
thanks www.movied.org
