### ISSUE TITLE
Implement support for system configuration files

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#130]
Currently, when we update one of the default config files such as `autoload.ini` or `config_handlers.ini`, users have to copy the changes to their project config files by hand.

I suggest we introduce "global" configuration files that ship with the framework. Those include only basic stuff the framework needs. It makes sense for these three, IMHO:
- autoload
- compile
- config_handlers

The files in webapp/config/ would extend or overwrite the directives from these files.

Also, we could add the possibility to overwrite the files entirely, which can make sense sometimes, especially for compile configurations.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
