### ISSUE TITLE
agavi CLI script not portable

### ISSUE THREAD

**Issue by ghost** [agavi/agavi#138]
The agavi CLI script uses bash syntax, but its shebang line points to sh.  This works on Linux, where sh is usually just a variant of bash.  However it will **not run at all** on more traditional UNIXes like Solaris.

this:

```
export AGAVI_INSTALLATION="/usr/local/lib/php/agavi"
export TEMPLATES_DIR=${AGAVI_INSTALLATION}/buildtools/code_templates
```

should be:

```
AGAVI_INSTALLATION=/usr/local/lib/php/agavi
TEMPLATES_DIR=${AGAVI_INSTALLATION}/buildtools/code_templates
export AGAVI_INSTALLATION TEMPLATES_DIR
```

This is a tiny mistake; but it has a big impact!

_(Originally posted to Trac by sheckler@…)_

**Comment by linuxjackto1** [comment]
thanks www.movied.org
