### ISSUE TITLE
Decouple rendering from Views

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#139]
As discussed on IRC, we will introduce the concept of Renderers which are returned by Views. There are two main reasons for this:
1. DRY. If you have shared functionality across Views, you don't have to subclass each implementation (PHPView, !SmartyView, XSLView) you're using, duplicating the code
1. We'll need separate execute() methods for different contexts and output methods. Without Renderers, we'd need to have separate classes_for each of them, which obviously sucks
This implementation will eliminate basically all of the problems we could see when we decided to support per-context (Web, Cellphone, Console, XMLRPC) and per-output-type (PDF, RSS, HTML for Web Context) support in views.

We decided that `setTemplate()`, `setDecoratorTemplate()`, `setSlot()`, `setAttribute()` etc methods will remain in the View so they are universal. The renderer is returned from within the View's `execute*()` method, as an implementation, so you can control some stuff before returning it. The renderer shall pull data from the View.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
