### ISSUE TITLE
Make all classes properly CamelCased

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#140]
[AgaviAdo](http://github.com/agavi/agavi/wiki/AgaviAdo)DBDatabase => [AgaviAdodbDatabase](http://github.com/agavi/agavi/wiki/AgaviAdodbDatabase)

[AgaviMy](http://github.com/agavi/agavi/wiki/AgaviMy)SQLStorage => [AgaviMysqlStorage](http://github.com/agavi/agavi/wiki/AgaviMysqlStorage)

AgaviPHPRenderer => [AgaviPhpRenderer](http://github.com/agavi/agavi/wiki/AgaviPhpRenderer)

AgaviHTTPSRequest => [AgaviHttpsRequest](http://github.com/agavi/agavi/wiki/AgaviHttpsRequest)

etc

**Comment by linuxjackto1** [comment]
thanks www.movied.org
