### ISSUE TITLE
DOS line endings in AgaviTranslationManager and other files

### ISSUE THREAD

**Issue by graste** [agavi/agavi#1511]
The AgaviTranslationManager has DOS line endings in it (probably introduced in #1008 :facepunch:). Other files in the repository are likely affected too. The mixed line endings should be fixed for the next release.

**Comment by ddelbondio** [comment]
i am not able to find any CRLF in the code :)

**Comment by graste** [comment]
Whatever made those disappear. :+1:

**Comment by dzuelke** [comment]
I converted all CRLF to LF during the Git migration :)

**Comment by graste** [comment]
:+1:
