### ISSUE TITLE
This project is dead, right?

### ISSUE THREAD

**Issue by va5ja** [agavi/agavi#1536]
March 2014: "We will start the 1.1 release cycle in 1-2 months from now." and "After 1.1 there will be at least one more minor release.".

**Comment by graste** [comment]
Well…it still works. :D

**Comment by va5ja** [comment]
And I still use it and thanks for your great FAQ :) What I had in mind is any further development or updates.

**Comment by guilhermeaiolfi** [comment]
It's the best framework for PHP yet... but it's kinda of sad that it will eventually die at this pace.

**Comment by ddelbondio** [comment]
Well, i wouldn't call it really dead, but just rather dormant right now. I still hope to change that in the nearer future, but right now I just don't have more time to put into it at my hands.

**Comment by graste** [comment]
Some pull requests have been merged. It's about time for a 1.0.8 maintainance and 1.1.0 with some smaller new features. Stay tuned. :-)

**Comment by DracoBlue** [comment]
:+1:

**Comment by thomasbachem** [comment]
See https://github.com/agavi/agavi/blob/master/CHANGELOG for details :)

**Comment by ddelbondio** [comment]
with the 1.0.8 release i think we can call the current state comatose, but alive
