### ISSUE TITLE
Call to undefined method AgaviTranslationManager and "No factory info for "security_filter""

### ISSUE THREAD

**Issue by DracoBlue** [agavi/agavi#1546]
Hello,

wie have a very heavy used agavi app (behind a varnish proxy, thousands of requests per second). This app works well, except when we clear the cache.

The error log is (sometimes) full of these messages:

``` log
[08-Apr-2015 16:03:13 Europe/Berlin] UncatchedException: exception 'AgaviException' with message 'No factory info for "security_filter"' in /mnt/nfs/agavitest/app/cache/config/logging.xml_production-live_web__e6c4b18324dd3f9c5a254948ebc6a1640cc11b64.php:337
[08-Apr-2015 17:13:35 Europe/Berlin] PHP Fatal error:  Call to undefined method AgaviTranslationManager::setLogger() in /mnt/nfs/agavitest/app/cache/config/logging.xml_production-live_web_9ee5c257ba5f5ba2165e0dedc190de69d03d9cb3.php
```

To fix that, we have to remove all files form `app/cache/*` and try again. After some time, it works.

I expect `agavi/config/AgaviConfigCache.class.php` to write the file in some incomplete manner as a racecondition from multiple php-fpm processes, which try to create the same (but incomplete) cache-files.

Anyone has these issues - or a fix for that?

**Comment by DracoBlue** [comment]
Maybe it's an apc issue.

http://php.net/manual/de/apc.configuration.php#ini.apc.file-update-protection
is 2 on the machine.

**Comment by DracoBlue** [comment]
After some investigation:

https://github.com/agavi/agavi/blob/master/src/config/AgaviConfigCache.class.php#L525

Writes the compile-file to a tmp-Directory and afterwards renames or copies the file to the real destination. Since in my use case the tmp-Directory and the target directory are two different mounts: the copy is used.

I assume that the copy is not fast enough AND the modified time of the cache file stays the same after copy  - thus the 2 seconds file-update-projection of apc is exceeded: apc caches half backed file.

How to fix it?

1. Put the tmp-file in the app/cache/config directory - so we are 100% sure that the file is on the same mount.
2. Remove the copy+unlink workaround for windows, since if it's in the app/cache/config-directory we can be sure that a rename will work.
3. Run touch on the renamed file to ensure that it's modified enough for apc to refresh the cache

Comments?

**Comment by graste** [comment]
Good catch, I guess!? :8ball:

**Comment by dzuelke** [comment]
> Since in my use case the tmp-Directory and the target directory are two different mounts: the copy is used.

Is that a hypothesis or did you observe that? Renaming across mounts should work, no? But that itself may not be an atomic operation in this case, as the file actually has to be copied first. Which means there's not a lot we can do?!

**Comment by DracoBlue** [comment]
Yep, it was a guess.

Similar issue to that one
http://serverfault.com/questions/397669/executed-php-files-are-stale-unitl-touched-symlinked-nfs-mount-as-web-root

I try to build a vagrant box with a testcase.

Am Freitag, 10. April 2015 schrieb David Zülke :

> Since in my use case the tmp-Directory and the target directory are two
> different mounts: the copy is used.
>
> Is that a hypothesis or did you observe that? Renaming across mounts
> should work, no? But that itself may not be an atomic operation in this
> case, as the file actually has to be copied first. Which means there's not
> a lot we can do?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agavi/agavi/issues/1546#issuecomment-91387079>.
>


-- 

  http://dracoblue.net

**Comment by DracoBlue** [comment]
The issue was caused by a nfs synchronisation issue. nfs agrecmax/min have been 60, while apc.file_update_protection was 10. Thus there were 50 seconds of inconsistent meta data, which broke apc's index.

Issue is closed for me.
