### ISSUE TITLE
Execution container request method consistency

### ISSUE THREAD

**Issue by MrHash** [agavi/agavi#1554]
https://github.com/agavi/agavi/blob/1.0/src/controller/AgaviController.class.php#L124-L126

If a request method for a particular route is application specific and not the default mapping from HTTP to Read/Write/Update/Delete, the method is lost when creating an execution container without specifying the execution method as an argument.

Would it not be better to propogate the execution method by using something like the following? Existing functionality would not change.
```
$this->context->getContainer()->getRequestMethod();
```

**Comment by ddelbondio** [comment]
The context, and thus AgaviController, doesn't have access to the current container. 
If you have access to the container, you can create a new one from there (https://github.com/agavi/agavi/blob/1.0/src/controller/AgaviExecutionContainer.class.php#L212). This will then pass the request method to the new container.
