### ISSUE TITLE
Override HTTP Request Method by using _method Parameter

### ISSUE THREAD

**Issue by DracoBlue** [agavi/agavi#1559]
In ruby on rails one is able to override the Request Method if it is POST. This is necessary, if you try to submit a form with DELETE/PUT/PATCH method, but the browser doesn't support it, yet.

So

    <form action="/user/123" method="delete"></form>

becomes

    <form action="/user/123?_method=delete" method="post"></form>

.

A patch can be found here: https://gist.github.com/3778104 The implementation allows overriding of the method only in case of a POST request. This way it's not possible to deeplink to a specific request method.

Do we need this in agavi?

**Comment by ddelbondio** [comment]
This is actually already possible with builtin features:

overwrite the AgaviWebRouting and define a custom source:
```php
class CustomWebRouting extends AgaviWebRouting {
  public function startup() {
    parent::startup();   
    $this->sources['_REQUEST'] = new AgaviRoutingArraySource($_REQUEST);
  }
}
```
Then in your routing.xml you can do:
```xml
<route name="method_switch" pattern="^(overwriteMethod:.+)$" source="_REQUEST[_method]" method="${overwriteMethod}" constraint="write" />
```
But you have to use the mapped method names (from https://github.com/agavi/agavi/blob/master/src/request/AgaviWebRequest.class.php#L327 or your config) in the _method request parameter.

@graste: something for your FAQ maybe?

**Comment by DracoBlue** [comment]
So users ALWAYS have to override the WebRouting to gain access to _method?

AFAIK it's impossible to use methods other then POST/GET im forms with modern browsers, without such workaround. So a executeDelete in Agavi can only be triggered by Javaecript in these browsers?

Do you really think one should fix that with a custom route + override WebRouting in eventuell y Agavi project to use a little more HTTP?

This patch is actually a standard patch, which we use for many projects. But since there is no such thing like a agavi-standard-edition (like in SF2), we can only put things in agavi core or in @graste's faq :(.
