### ISSUE TITLE
Agavi.org is down

### ISSUE THREAD

**Issue by Pictor13** [agavi/agavi#1580]
I can't reach it anymore since weeks.

Also, would be nice to have the useful IRClogs also somewhere else than just there :)

**Comment by Pictor13** [comment]
It came back up & running. Thanks God (or the admins).

**Comment by sonampenjor** [comment]
I can't reach agavi today.. It was accessible last week.

**Comment by Pictor13** [comment]
It is down again 🙁
Seems to happen regularly. Not sure if it comes up by itself, or if there is some hosting fee that is paid too late.

@dzuelke I suppose you keep paying the hosting. Do you need any contribution for it?

The website is a good resource (one of the few), especially for the the last 10+ years of IRC logs, where one can find insights about specifics that are not mentioned in the Agavi Definite Guide, in the Wiki, in Graste's FAQ or on DracoBlue's Blog.

**Comment by Pictor13** [comment]
The website is gone definitely.\
See [ae0a914](https://github.com/agavi/agavi/commit/ae0a914d2cba93e595571d0b90bc11bbe3293e54).

There is still something on the Wayback Machine:
* http://web.archive.org/web/20170826204121/http://www.agavi.org/
* http://web.archive.org/web/20181108235937/http://www.agavi.org/documentation/tutorial

Unfortunately all the IRC logs have not been fetched by Archive.org. But they were containing good convos, hints, details of use and of implementation.
I have a backup of the logs till January 2018.\
If anybody is interested I can put them on a repository (even though it would be better to first clarify licensing & privacy concerns).
