### ISSUE TITLE
Command line support (request/response/routing)

### ISSUE THREAD

**Issue by Xylakant** [agavi/agavi#480]
This is my stab at implementing a console request/routing/response. With routing, the command gets called like this: 

cli.php <command> -param1 paramvalue1 -param2 -param3 paramvalue3

Without routing, the call is like this:

cli.php <module.action> -param1 paramvalue1 -param2 -param3 paramvalue3

All arguments that start with a dash(-) or double dash (--) will be regarded as paramname and the following argument as param value if it does not start with a dash or double dash. Parameters that have no following argument will be set to "true" to indicate that they have been passed.

**Comment by Pictor13** [comment]
I'm wondering if this already supports the PHP automatic parsing as array for the parameters:

    cli.php -param1[] paramvalue1 -param2[key] paramvalue2 -param3[key][subkey] paramvalue3

Or I am doing it wrong?
