### ISSUE TITLE
Full content-type support

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#81]
We really should have methods that allow to set the content-type at runtime. Parents would override children's content types, forwards have to be taken into account, also watch out for Render::VAR and Render::NONE.
Stack traces should obey this, but that's not that big of a deal IMO.
This mainy affects [WebController](http://github.com/agavi/agavi/wiki/WebController). It might also be a good idea to hard-code default content types inside controllers, and get rid of that settings.ini CONTENT_TYPE directive. After all, it's not needed for [ConsoleControllers](http://github.com/agavi/agavi/wiki/ConsoleControllers) and the like... mmh...
We have to get this right in the first place, it shouldn't have an afterthought taste or so.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
