### ISSUE TITLE
A way of handling agavi-exceptions in user code

### ISSUE THREAD

**Issue by horros** [agavi/agavi#86]
I created patches to Context, [ConsoleController](http://github.com/agavi/agavi/wiki/ConsoleController), [PageWebController](http://github.com/agavi/agavi/wiki/PageWebController) and [FrontWebController](http://github.com/agavi/agavi/wiki/FrontWebController) that allows you to catch [AgaviExceptions](http://github.com/agavi/agavi/wiki/AgaviExceptions) and forward them to a user-defined module/action pair. This basically sprung from the fact that our users
will get a heart attack if they click something and suddenly a big red box with bold red text with some arcane code in it appears on the screen :)

This is a very unobtrusive patch. If you haven't defined AG_ERROR_MODULE and AG_ERROR_ACTION (in settings.ini) to point to a module/action pair that handles the exception (ie. makes a pretty error message), the exception is printed like it always has been, ie stack trace is printed to the screen. Same thing happens if an exception is thrown in the exception handler module (or in the path from handleException()).

I sent the patches to the mailing list, since I couldn't figure out a way to attach them here.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
