### ISSUE TITLE
Add option for persistent connections in PDODatabase class

### ISSUE THREAD

**Issue by ghost** [agavi/agavi#87]
Attached patch adds support for 'param.persistent' on PDO database connections.

Page render timing results (simple SQL select, approx. 30 records):
- non-persistent: 0.0760s
- persistent: 0.0197s

Significant overhead is present in the database auth stage, especially on small transactions.

_(Originally posted to Trac by pressureman@…)_

**Comment by linuxjackto1** [comment]
thanks www.movied.org
