### ISSUE TITLE
"agavi project" should create default error actions and set the correct modules in settings.ini

### ISSUE THREAD

**Issue by dzuelke** [agavi/agavi#89]
ERROR_404_*
LOGIN_*
MODULE_DISABLED_*
SECURE_*
UNAVAILABLE_*

Also, the respective module should be set correctly, not always "Default". Maybe the first module entered, or the user has to define one of them when running the project task. This would also set the DEFAULT_\* settings.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
