### ISSUE TITLE
agavi script doens't work on Solaris

### ISSUE THREAD

**Issue by ghost** [agavi/agavi#90]
The Agavi script doens't work on Solaris 10 because #!/bin/sh on Solaris is the Bourne shell, while on Linux it's the Bourne Again shell. 

Bourne does not support the syntax:
export FOO=bar

The following does work and should also work for bash:
FOO=bar
export FOO

Also after splitting this out, lines like PWD_PATH = $(pwd) give me a syntax error.

/opt/csw/php5/bin/agavi: syntax error at line 24: `PWD_PATH=$' unexpected

Changing it to PWD_PATH = ${pwd} lets the script work, but I get a message:
/opt/csw/php5/bin/agavi: }: not found

So it doesn't seem to be the complete solution. Maybe someone with actual shell scripting knowledge can fix it.

_(Originally posted to Trac by kador@…)_

**Comment by linuxjackto1** [comment]
thanks www.movied.org
