### ISSUE TITLE
ValidatorManager triggers Notice: Array to string conversion

### ISSUE THREAD

**Issue by ghost** [agavi/agavi#91]
When processing array values posted from a form, the [ValidatorManager](http://github.com/agavi/agavi/wiki/ValidatorManager) generates a "Array to string conversion" notice because it assumes that the value will always be a string.

```
<form>
<input type="text" name="location[country_code]" />
<input type="text" name="location[postal_code]" />
<input type="submit" name="submit" />
</form>
```

$value retrieved from request will be an array:

```
Array
{
  [country_code] => US
  [postal_code] = > 78609
}
```

src/validator/ValidatorManager.class.php on [Line 318](http://trac.agavi.org/trac.cgi/browser/trunk/src/validator/ValidatorManager.class.php#L318):

```
if ($value == null || strlen($value) == 0)

```

Because $value is an array, the strlen() generates the notice.

Should be amended to:

```
if ($value == null || (!is_array($value) && strlen($value) == 0) || (is_array($value) && sizeof($value) == 0))

```

_(Originally posted to Trac by "Jonathan Wilson")_

**Comment by linuxjackto1** [comment]
thanks www.movied.org
