### ISSUE TITLE
The SmartyView should include Smarty.class.php in a more "correct" way.

### ISSUE THREAD

**Issue by ghost** [agavi/agavi#92]
Currently, it is being loaded through:

```
require_once(AG_SMARTY_DIR.'/libs/Smarty.class.php');
```

This requires the AG_SMARTY_DIR constant to be set which could be ok, but including "libs" in the path is certainly not OK. If you are using Smarty through a standard install, the correct way (according to the Smarty documentation) is to include only "Smarty.class.php". To make this code further compatible with other, I would suggest checking if Smarty has already been loaded (using class_exists()). We use smarty for formatting mail as well (logic that will be executed before the [SmartyView](http://github.com/agavi/agavi/wiki/SmartyView) is), and therefore Smarty is loaded twice (fatal error!) unless we apply our in-house patches. 

Suggested code:

```
if (!class_exists('Smarty'))
{
    require_once('smarty/Smarty.class.php');
}
```

Note that this suggested code would work if Smarty is installed in a PEAR-esque fashion (and this is a policy decision for the Agavi-developers, since Smarty is not actually a pear-package).

_(Originally posted to Trac by johan.mjones@…)_

**Comment by linuxjackto1** [comment]
thanks www.movied.org
