### ISSUE TITLE
Template collisions with SmartyView

### ISSUE THREAD

**Issue by umesecke** [agavi/agavi#97]
my setup:

```
htdocs
 `-index.php
webapp
 +-modules
 | +-Default
 | | +-templates
 | | `-...
 + +-News
 | | +-templates
 | | `-...
 | `-...
 `-...
smarty
 +-templates_c
 +-configs
 `-cache
```

The modules Default and News both have a templates named [IndexSuccess](http://github.com/agavi/agavi/wiki/IndexSuccess).tpl. Now when I display Default/Index(Success) and after that News/Index(Success), then News/Index(Success) displays the Content from Default/Index(Success).

This is because Smarty only indexes compiled templates by what is given in $tmpl_name when calling smarty::display/fetch($tmpl_name) and because both module have different template_dirs, that $tmpl_name is the same in both modules.

See also:
- http://www.phpinsider.com/smarty-forum/viewtopic.php?t=3442
- http://www.phpinsider.com/smarty-forum/viewtopic.php?p=12732

There are two work-arounds given:
1. using a seperate template_c-directory for each template-dir
1. changing the string given to display()/fetch() by moving smarty::template_dir and prepending the relativ path to the template-files

As Smarty-upstream apparently doesn't intent to fix that issue, I implemented the 2nd work-around in [SmartyView](http://github.com/agavi/agavi/wiki/SmartyView).

```
--- SmartyView.class.php.orig   2006-02-19 05:52:05.000000000 +0100
+++ SmartyView.class.php        2006-02-19 06:27:07.000000000 +0100
@@ -120,15 +120,16 @@
                // get the render mode
                $mode = $this->getContext()->getController()->getRenderMode();

-               $this->getEngine()->template_dir = $this->getDirectory();
+               $this->getEngine()->template_dir = AG_WEBAPP_DIR;
                $this->getEngine()->compile_dir  = AG_SMARTY_CACHE_DIR;
+               $rel_tmpl_path = str_replace(AG_WEBAPP_DIR.'/', '', $this->getDirectory());

                if ($mode == View::RENDER_CLIENT && !$this->isDecorator()) {
                        // render directly to the client
-                       $this->getEngine()->display($this->getTemplate());
+                       $this->getEngine()->display($rel_tmpl_path.'/'.$this->getTemplate());
                } else if ($mode != View::RENDER_NONE) {
                        // render to variable
-                       $retval = $this->getEngine()->fetch($this->getTemplate());
+                       $retval = $this->getEngine()->fetch($rel_tmpl_path.'/'.$this->getTemplate());

                        // now render our decorator template, if one exists
                        if ($this->isDecorator()) {
```

The patch sets AG_WEBAPP_DIR as smarty's template_dir instead of the full module's template-path. The relative path from AG_WEBAAP_DIR to the templates is prepended to the template's name.

With that modification now both modules reder their own templates and bypass smarty's indexing-problem.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
